### ISSUE TITLE
change port

### ISSUE THREAD

**Issue by danielbadry** [kibatic/docker-proftpd#2]
hi
after change port in docker-compose.yml and Dockerfile , user can login to ftp but get error . Failed to retrieve directory listing .
i change network mode but not working.
help me to change default port .
@philippe-levan

**Comment by philippe-levan** [comment]
I believe the problem is a misconfiguration of the ftp client between passive or active connection. By the way, you can also change the configuration of this bundle.

network_mode = host means that the ports that the container listens are directly linked to the ports of the host. For FTP, you have to do that because you don't know which port will be used (FTP is a strange protocol). So let the network_mode to host, everything will be much simpler.

If you want to change the configuration of the proftpd server (for example for changing ports), you have to modify the file /etc/proftpd/proftpd.conf (perhaps by sharing a volume with the host).

I let you check the documentation of proftpd for setting these configurations. I don't know these configuration because I always use the basic configuration of proftpd.

**Comment by Avalancs** [comment]
Although this issue has already been closed, I would recommend two alternative solutions for anyone looking to do this:
Solution 1: If you don't use `network_mode = host` then you can just remap the exposed port in docker or docker compose, do not change it inside the configuration. The port exposed inside the Dockerfile is just "documentation" so changing it there doesn't affect anything.

For docker command you can use `-p` flag, so `-p 8080:21` would map port 21 (the default ftp port) from inside the container to 8080 on the host machine, and you could connect to 8080 with your ftp client. If you use `-p` then the exposed ports from inside the Dockerfile might not get exposed, so don't forget to expose your passive ftp ports as well, e.g.: `-p 50000-50100:50000-50100`

For docker compose there is the `ports` section where you can do the same:
```yaml
    ports:
      - 8080:21
      - 50000-50100:50000-50100
```

Solution 2: You don't have to override `/etc/proftpd/proftpd.conf` just to add/change some configuration, you can mount your own configuration file under the `/etc/proftpd/conf.d/` folder and it will be read during startup. This allows you to add configuration without having to create your own docker image.

For your case to change to using port 8080 you would have a file mounted to e.g.: `/etc/proftpd/conf.d/proftpd-port.conf` with the contents:

```
Port 8080
```
